name: Python CI

on:
  push:
    branches: [ robot_code ]
  pull_request:
    branches: [ robot_code ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: robot
          POSTGRES_PASSWORD: Access_for_robot_12345
          POSTGRES_DB: warehouse_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev python3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary pytest
        pip install -e .

    - name: Copy graph.csv to src
      run: |
        cp graph.csv src/graph.csv

    - name: Run tests
      env:
        PGUSER: robot
        PGPASSWORD: Access_for_robot_12345
        PGHOST: localhost
        PGPORT: 5432
        PGDATABASE: warehouse_db
      run: |
        pytest -v